### ISSUE TITLE
Clarify status of this ETS

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-sta-client10#2]
@taniakhalafbeigi Is there already an ETS for STA 1.0 Client available? Or are there any plans to implement one? Otherwise the repository can be deleted.

**Comment by taniakhalafbeigi** [comment]
There is a plan to develop a test suite for SensorThings Clients. It was discussed to be a SensorThings proxy that the clients can send requests to, and then basically their requests will be evaluated by the test suite.
We spend some time on its design and we needed help for how to prepare that proxy for TEAMEngine.
Based on my current information there will be contribution to this repository.

**Comment by lgoltz** [comment]
@taniakhalafbeigi Thanks for clarification. I've created a new ticket: #3
